apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/anungbisa4/b2b-cms:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/anungbisa4/b2b-cms:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: b2b-cms
        chartPath: charts/b2b-cms
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/anungbisa4/b2b-cms"
          image.tag: "{{.DIGEST_HEX}}"
